#!/bin/bash

git filter-branch -f --commit-filter '
if [ "$GIT_AUTHOR_EMAIL" = "jiewei.ljw@alibaba-inc.com" ];
then
GIT_AUTHOR_NAME="echopi";
GIT_AUTHOR_EMAIL="eagleking0213@gmail.com";
git commit-tree "$@";
else
git commit-tree "$@";
fi' HEAD
